spring:
  application:
    name: demoAuditoria

  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.db}?currentSchema=${postgres.schema_default}
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      maximum-idle: 10
      pool-name: master

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.globally_quoted_identifiers: true

      # Configs do Envers
      org.hibernate.envers.default_schema: ${postgres.schema_audit}
      org.hibernate.envers.audit_table_suffix: "_aud"
#      org.hibernate.envers.audit_table_prefix: ""

      # Revisões
      org.hibernate.envers.store_data_at_delete: true
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.modified_flag_suffix: "_mod"
      org.hibernate.envers.audit_strategy: "org.hibernate.envers.strategy.ValidityAuditStrategy"
      org.hibernate.envers.audit_strategy_validity_store_revend_timestamp: true

      # Exclusões e performance
      org.hibernate.envers.audit_empty_revisions: false
      org.hibernate.envers.track_entities_changed_in_revision: true
#      org.hibernate.envers.do_not_audit_optimistic_locking_field: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration/system,classpath:db/migration/audit
    schemas: ${postgres.schema_default},${postgres.schema_audit}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  undertow:
    threads:
      worker: 64
      io: 4

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: none
    operations-sorter: alpha
    filter: true