server:
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  jpa:
    properties:
      jakarta: # Scrip para geração de migration
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/db/hibernate/db_create.sql
              drop-target: src/main/resources/db/hibernate/db_drop.sql
              update-target: src/main/resources/db/hibernate/db_update.sql

postgres:
  url: localhost:5432
  username: postgres
  password: postgres
  db: core_app
  schema_default: core_system
  schema_audit: core_audit

clickhouse:
  url: localhost:8123
  username: clickhouse
  password: clickhouse
  db: core_audit
  schema_default: core_system