create table "profile_permissions"
(
    "profile_id" bigint       not null,
    "permission" varchar(255) not null ,
    primary key ("profile_id", "permission")
);
create table "profiles"
(
    "id"          bigint generated by default as identity,
    "created_at"  timestamp(6) with time zone not null,
    "updated_at"  timestamp(6) with time zone not null,
    "version"     bigint,
    "description" varchar(255),
    "name"        varchar(255),
    primary key ("id")
);
create table "tokens"
(
    "id"            bigint generated by default as identity,
    "created_at"    timestamp(6) with time zone not null,
    "updated_at"    timestamp(6) with time zone not null,
    "version"       bigint,
    "token_expired" boolean,
    "token_revoked" boolean,
    "token_type"    varchar(255),
    "token_value"   varchar(2000),
    "user_id"       bigint,
    primary key ("id")
);
create table "users"
(
    "id"         bigint generated by default as identity,
    "created_at" timestamp(6) with time zone not null,
    "updated_at" timestamp(6) with time zone not null,
    "version"    bigint,
    "email"      varchar(255),
    "name"       varchar(255),
    "password"   varchar(255),
    "profile_id" bigint,
    primary key ("id")
);

alter table if exists "users"
    drop constraint if exists "UK6j5t70rd2eub907qysjvvd76n";
alter table if exists "users"
    add constraint "UK6j5t70rd2eub907qysjvvd76n" unique ("email");
alter table if exists "profile_permissions"
    add constraint fk_profile_permissions_profile foreign key ("profile_id") references "profiles";
alter table if exists "tokens"
    add constraint "FKck21ekaqng736h8ohx6l9xrgv" foreign key ("user_id") references "users";
alter table if exists "users"
    add constraint "FKp7uo6jchripnsh2wnwskur7ag" foreign key ("profile_id") references "profiles";