create table "autores"
(
    "id"         bigint generated by default as identity,
    "created_at" timestamp(6) with time zone not null,
    "updated_at" timestamp(6) with time zone not null,
    "version"    bigint,
    "nome_autor" varchar(250)                not null,
    primary key ("id")
);
create table "detalhes"
(
    "id"             bigint generated by default as identity,
    "created_at"     timestamp(6) with time zone not null,
    "updated_at"     timestamp(6) with time zone not null,
    "version"        bigint,
    "isbn_codigo"    varchar(255),
    "editora_nome"   varchar(255),
    "num_paginas"    integer,
    "ano_publicacao" integer,
    "livro_id"       bigint,
    primary key ("id")
);
create table "exemplares"
(
    "id"            bigint generated by default as identity,
    "created_at"    timestamp(6) with time zone not null,
    "updated_at"    timestamp(6) with time zone not null,
    "version"       bigint,
    "codigo_barras" varchar(255),
    "is_disponivel" boolean,
    "livro_id"      bigint,
    primary key ("id")
);
create table "livro_autor_assoc"
(
    "livro_id" bigint not null,
    "autor_id" bigint not null,
    primary key ("livro_id", "autor_id")
);
create table "livros"
(
    "id"         bigint generated by default as identity,
    "created_at" timestamp(6) with time zone not null,
    "updated_at" timestamp(6) with time zone not null,
    "version"    bigint,
    "titulo"     varchar(255)                not null,
    primary key ("id")
);

alter table if exists "detalhes"
    drop constraint if exists idx_isbn_codigo;
alter table if exists "detalhes"
    add constraint idx_isbn_codigo unique ("isbn_codigo");
alter table if exists "detalhes"
    drop constraint if exists "UK7omhl5j6efrra1gseoyoamaxc";
alter table if exists "detalhes"
    add constraint "UK7omhl5j6efrra1gseoyoamaxc" unique ("livro_id");
alter table if exists "exemplares"
    drop constraint if exists idx_codigo_barras;
alter table if exists "exemplares"
    add constraint idx_codigo_barras unique ("codigo_barras");
alter table if exists "detalhes"
    add constraint fk_detalhe_livro foreign key ("livro_id") references "livros";
alter table if exists "exemplares"
    add constraint fk_exemplar_livro foreign key ("livro_id") references "livros";
alter table if exists "livro_autor_assoc"
    add constraint fk_livro_autor_autor foreign key ("autor_id") references "autores";
alter table if exists "livro_autor_assoc"
    add constraint fk_livro_autor_livro foreign key ("livro_id") references "livros";